[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SPI2Py"
version = "0.0.1"
authors = [
  { name="Chad Peterson", email="cp44@illinois.edu" },
]
description = "Spatial packaging of interconnected systems with physical interactions"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.pytest.ini_options]
pythonpath = [
  "SPI2Py/src/SPI2Py/","SPI2Py/src/SPI2Py/utils",
]

[project.urls]
"Homepage" = "https://github.com/SPI2Py/SPI2Py"
"Bug Tracker" = "https://github.com/SPI2Py/SPI2Py/issues"