[info]
name = "Chad Peterson"
description = """Demo Problem"""

[problem]
objective = "bounding box volume"

[domain.engine]
filepath='cad_models/engine.stl'

[domain.engine_volume_front]
filepath='cad_models/engine_vol_front.stl'
color = 'green'

[domain.engine_volume_middle]
filepath='cad_models/engine_vol_mid.stl'
color = 'blue'

[domain.engine_volume_rear]
filepath='cad_models/engine_vol_rear.stl'
color = 'purple'

[components.gear1]
filepath='part_models/radiator_and_ion_exchanger.xyzr'
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='purple'

[components.radiator_and_ion_exchanger_1b]
filepath='part_models/radiator_and_ion_exchanger.xyzr'
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='purple'

