[info]
name = "Chad Peterson"
description = """Demo Problem"""

[problem]
objective = "bounding box volume"

[domain.engine]
filepath='cad_models/engine.xyzr'
prescale = 1
color = 'grey'

[domain.engine_volume_fwd]
filepath='cad_models/engine_vol_fwd.xyzr'
prescale = 1
color = 'green'


[domain.engine_volume_middle]
filepath='cad_models/engine_vol_mid.xyzr'
prescale = 1
color = 'blue'


[domain.engine_volume_rear]
filepath='cad_models/engine_vol_rear.xyzr'
prescale = 1
color = 'purple'

[components.stepper_gear]
filepath='Thingi10k_models/stepper_gear.xyzr'
prescale = 0.1
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='#FD3223'

[components.basic_ring]
filepath='Thingi10k_models/basic_ring.stl.xyzr'
prescale = 0.1
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='#020686'

[components.CrossHead_Pin]
filepath='Thingi10k_models/CrossHead_Pin.stl.xyzr'
prescale = 0.1
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='#FDBF23'

