[info]
name = "Chad Peterson"
description = """Demo Problem"""

[problem]
objective = "bounding box volume"

[domain.engine]
filepath='cad_models/engine.xyzr'
color = 'grey'

[domain.engine_volume_fwd]
filepath='cad_models/engine_vol_fwd.xyzr'
color = 'green'

[domain.engine_volume_middle]
filepath='cad_models/engine_vol_mid.xyzr'
color = 'blue'

[domain.engine_volume_rear]
filepath='cad_models/engine_vol_rear.xyzr'
color = 'purple'

[components.stepper_gear]
filepath='Thingi10k_models/stepper_gear.xyzr'
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='#FD3223'

[components.basic_ring]
filepath='Thingi10k_models/basic_ring.stl.xyzr'
degrees_of_freedom=['x', 'y', 'z', 'rx', 'ry', 'rz']
color='#020686'

