engine.translation = [0, 0, 0]
engine.rotation= [0, 0, 0]

engine_volume_fwd.translation = [0, 0, 0]
engine_volume_fwd.rotation= [0, 0, 0]

engine_volume_middle.translation = [0, 0, 0]
engine_volume_middle.rotation= [0, 0, 0]

engine_volume_rear.translation = [0, 0, 0]
engine_volume_rear.rotation= [0, 0, 0]

stepper_gear.translation = [0, 0, 0]
stepper_gear.rotation= [0, 0, 0]

basic_ring.translation = [0, 0, 0]
basic_ring.rotation= [0, 0, 0]

CrossHead_Pin.translation = [0, 0, 0]
CrossHead_Pin.rotation= [0, 0, 0]

