Input Filepath : Input/input.yaml
Output Filepath : Output/output.json

geometry:

  # The number of bends per each interconnect
  bends per interconnect: 1

solver:

  # The number of random initial layouts and subsequent optimizations
  number of solutions: 1

  # A tolerance of 2.5e-1 seems to work good enough without slowing things down, use 1e-1 for better precision
  convergence tolerance: 2.5e-1

  # 0 to 1; 0 means no collision, >0 means some collision
  component_component_collision_tolerance: 0
  component_interconnect_collision_tolerance: 0.5
  interconnect_interconnect_collision_tolerance: 0.5
  structure_all_collision_tolerance: 0

visualization :

  # Value between 0 and 20
  resolution: 8

  # true or false; should the program generate a GIF? Warning, generating GIFs increases the runtime
  output_gif: false



