Inputs:

  Folderpath: Input/
  Filename : input_demo.yaml
  User: Chad Peterson


Geometry:

  # The number of bends per each interconnect
  bends per interconnect: 1

Solver:

  # The number of random initial layouts and subsequent optimizations
  number of solutions: 1

  # Tolerances between 1e-1 and 2.5e-1 solve within a reasonable time
  convergence tolerance: 2.5e-1

  # 0 to 1; 0 means no collision, >0 means some collision
  component_component_collision_tolerance: 0
  component_interconnect_collision_tolerance: 0.5
  interconnect_interconnect_collision_tolerance: 0.5
  structure_all_collision_tolerance: 0

Visualization:

  # Value between 0 and 20
  # Corresponds to...
  resolution: 8

  # true or false; should the program generate a GIF?
  # Warning, generating GIFs increases the runtime
  Output GIF: false
  GIF Filename: geometric_optimization


Outputs:

  Folderpath: Output/
  Report Filename: output.json



