# Configuration File
# Sections: data, analysis, layout, optimization, results
# data: ...
# analysis: ...
# layout: ...
# optimization: ...
# results: ...

Username: Placeholder
Problem Description: Placeholder


data:
  placeholder: placeholder


analysis:

  # Specify whether to check for collision between specific pairs
  check collisions:
    components and components: true
    components and interconnects: true
    components and structures: false
    interconnects and interconnects: true
    interconnects and structures: false

  # Specify which constraint function should be used
  collision detection methods:
    components and components: tbd
    components and interconnects: tbd
    components and structures: tbd
    interconnects and interconnects: tbd
    interconnects and structures: tbd

  # 0 to 1; 0 means no collision, >0 means some collision
  collision tolerance:
    components and components: 0
    components and interconnects: 0
    components and structures: 0
    interconnects and interconnects: 0
    interconnects and structures: 0

  objective scaling factor: 1/50


layout:

  # The number of random initial layouts and subsequent optimizations
  # Not currently used
  number of solutions: 1


optimize:

  # Solver
  # TODO Add more solvers
  solver: scipy.optimize.minimize

  # Method
  # TODO Add more methods
  method: trust-constr

  # TODO Specify objective function
  # TODO Specify constraint function

  # Tolerances between 1e-1 and 2.5e-1 solve within a reasonable time
  convergence tolerance: 2.5e-2


results:

  Report Filename: report.json
  GIF Filename: geometric_optimization.gif

  plot:
    x limits: [-5, 5]
    y limits: [-5, 5]
    z limits: [-5, 5]

    # Resolution of each individual sphere
    # Value between 3 and 20
    resolution: 12





