[components]

[components.0]
description = 'Component 0'
filepath='models/Bot_Eye.xyzr'
n_spheres=10
ports = [[-1.5, 0, 0], [1.5, 0, 0]]
color='purple'

[components.1]
description = 'Component 1'
filepath='models/CogDrivenGear.xyzr'
n_spheres=10
ports = [[-1.5, 0, 0], [1.5, 0, 0]]
color='purple'

[components.2]
description = 'Component 2'
filepath='models/CrossHead_Pin.xyzr'
n_spheres=10
ports = [[0, -0.35, 0], [0, 0.35, 0]]
color='blue'


[interconnects]

[interconnects.0]
component_1 = 0
port_1 = 1
component_2 = 1
port_2=0
n_segments=2
n_spheres_per_segment=10
radius=0.15
color='black'

[interconnects.1]
component_1=1
port_1=1
component_2=2
port_2=0
n_segments=2
n_spheres_per_segment=10
radius=0.15
color='black'

[interconnects.2]
component_1=2
port_1=1
component_2=0
port_2=0
n_segments=2
n_spheres_per_segment=10
radius=0.15
color='black'



