[components.0]
name = 'radiator_and_ion_exchanger_1a'
spheres_filepath='part_models/radiator_and_ion_exchanger.xyzr'
port_indices = [0, 1]
port_positions = [[-1.475, 0, 0], [1.475, 0, 0]]
color='purple'

[components.1]
name = 'radiator_and_ion_exchanger_1b'
spheres_filepath='part_models/radiator_and_ion_exchanger.xyzr'
port_indices = [0, 1]
port_positions = [[-1.475, 0, 0], [1.475, 0, 0]]
color='purple'

[components.2]
name = 'pump_2a'
spheres_filepath='part_models/pump.xyzr'
port_indices = [0, 1]
port_positions = [[-1.475, 0, 0], [1.475, 0, 0]]
color='blue'

[components.3]
name = 'pump_2b'
spheres_filepath='part_models/pump.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.275, 0], [0, -0.275, 0]]
color='blue'

[components.4]
name = 'particle_filter_3a'
spheres_filepath='part_models/particle_filter.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.215, 0], [0, -0.215, 0]]
color='yellow'

[components.5]
name = 'particle_filter_3b'
spheres_filepath='part_models/particle_filter.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.215, 0], [0, -0.215, 0]]
color='yellow'

[components.6]
name = 'fuel_cell_stack_4a'
spheres_filepath='part_models/fuel_cell_stack.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.85, 0], [0, -0.85, 0]]
color='green'

[components.7]
name = 'fuel_cell_stack_4b'
spheres_filepath='part_models/fuel_cell_stack.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.85, 0], [0, -0.85, 0]]
color='green'

[components.8]
name = 'WEG_heater_and_pump_5'
spheres_filepath='part_models/WEG_heater_and_pump.xyzr'
port_indices = [0, 1]
port_positions = [[0, 0.9665, 0], [-0.8775, 0, 0]]
color='gray'

[components.9]
name = 'heater_core_6'
spheres_filepath='part_models/heater_core.xyzr'
port_indices = [0, 1]
port_positions = [[0, -0.7225, 0], [0, 0.7225, 0]]
color='red'

[interconnects.0]
component_1 = 0
port_1 = 1
component_2 = 1
port_2='left'
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.1]
component_1=1
port_1=1
component_2=3
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.2]
component_1=3
port_1=1
component_2=5
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.3]
component_1=5
port_1=1
component_2=7
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.4]
component_1=7
port_1=1
component_2=8
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.5]
component_1=8
port_1=1
component_2=9
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.6]
component_1=9
port_1=1
component_2=6
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.7]
component_1=6
port_1=1
component_2=4
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.8]
component_1=4
port_1=1
component_2=2
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'

[interconnects.9]
component_1=2
port_1=1
component_2=0
port_2=0
n_segments=3
n_spheres_per_segment=25
radius=0.05
color='black'



