[info]
name = "Chad Peterson"
description = "A simple example of a 3D model of a control valve and actuator"

[geometry]

[geometry.components]

[geometry.conductors]


[kinematics]

[projection]

[finite_element]




  control_valve_1: name: control_valve_1,
      color: aquamarine,
      degrees_of_freedom:(x, y, z, rx, ry, rz),
      filepath: part_models/control_valve_1.xyzr,
      ports:
        -name: supply, origin: [2, 1, 2.5], radius: 0.5,
        -name: return, origin: [4, 1, 2.5], radius: 0.5})

  actuator_1: name: actuator_1,
       color: orange,
       degrees_of_freedom:(x, y, z, rx, ry, rz),
       filepath:part_models/actuator_1.xyzr,
       ports:
          -name: supply, origin: [1, 0, 1], radius: 0.5},
          -name: return, origin: [2, 0, 1], radius: 0.5}])

  c2 : name:component_2,
                 color:indigo,
                 degrees_of_freedom:(x, y, z, rx, ry, rz),
                 filepath:part_models/component_2.xyzr)
  
  c3 : name:component_3,
                 color:olive,
                 degrees_of_freedom:(x, y, z, rx, ry, rz),
                 filepath:part_models/component_3.xyzr)
  
  c4 : name:structure_1,
                 color:gray,
                 degrees_of_freedom:(),
                 filepath:part_models/structure_1.xyzr)

interconnects:


  ic0: 
    name:hp_cv_actuator,
    color:black,
    component_1_name:control_valve_1,
    component_1_port_index:c0.port_indices[supply],
    component_2_name:actuator_1,
    component_2_port_index:c1.port_indices[supply],
    radius:0.25,
    number_of_waypoints:2,
    degrees_of_freedom:(x, y, z))

  ic1:
    name:lp_cv_actuator,
    color:blue,
    component_1_name:control_valve_1,
    component_1_port_index:c0.port_indices[return],
    component_2_name:actuator_1,
    component_2_port_index:c1.port_indices[return],
    radius:0.25,
    number_of_waypoints:1,
    degrees_of_freedom:(x, y, z))